### ISSUE TITLE
Feature request: Build linux/arm64/v8 images

### ISSUE THREAD

**Issue by reneleonhardt** [bell-sw/Alpaquita#1]
I just found out about alpaquita-linux-base, what an amazing image, thank you for providing security-oriented images while Alpine itself hasn't been updated for 3 months even when it contains multiple CVEs!

When I look at the architectures in [bellsoft/alpaquita-linux-base](https://hub.docker.com/r/bellsoft/alpaquita-linux-base/tags) I can see the most important one linux/`amd64`, would it be possible to add the second most important one linux/`arm64`/v8?

I will try to migrate from distroless/python3-debian12 to alpaquita-linux-python, I hope 3.12 builds will be added soon.
Is it possible to contribute? Then I could add them myself 😄

Thank you for all your hard work!

**Comment by magnus-larsson** [comment]
Any updates on this issue?

I really would like to try out [bellsoft/alpaquita-linux-base](https://hub.docker.com/r/bellsoft/alpaquita-linux-base/tags) on my MBP M1 & RPi 😀

Let me know if I can help out testing it on ARM64!

**Comment by reneleonhardt** [comment]
I don't know more than you, the maintainers never reacted to my reasonable feature request 😅
Interestingly enough, they answered [another issue](https://github.com/bell-sw/Alpaquita/issues/3) after 3 days, but not mine... makes you think 🤔

**Comment by voitylov** [comment]
The request is more than reasonable. I would kindly ask for some patience with this, for a month or so.

**Comment by voitylov** [comment]
Alpaquita for AArch64 is publicly available: https://bell-sw.com/pages/downloads/alpaquita/
